const data = {
  products: [
    {
      _id: '1',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/download.jpg',
      price: 1500,
      brand: 'Raymond',
      rating: 4.5,
      numReview: 10,
      countInStock: 4,
    },
    {
      _id: '2',
      name: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/download.jpg',
      price: 1500,
      brand: 'Raymond',
      rating: 4.5,
      numReview: 10,
      countInStock: 4,
    },
    {
      _id: '3',
      name: 'Fit pant',
      category: 'Pants',
      image: '/images/download.jpg',
      price: 1500,
      brand: 'Raymond',
      rating: 4.5,
      numReview: 10,
      countInStock: 6,
    },
    {
      _id: '4',
      name: 'Fit pant',
      category: 'Pants',
      image: '/images/download.jpg',
      price: 1500,
      brand: 'Raymond',
      rating: 4.5,
      numReview: 10,
      countInStock: 4,
    },
  ],
};
module.exports = data;
