export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'; 
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST';
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';


export const PRODUCT_LIST_MEN_REQUEST = 'PRODUCT_LIST_MEN_REQUEST';
export const PRODUCT_LIST_MEN_SUCCESS = 'PRODUCT_LIST_MEN_SUCCESS';
export const PRODUCT_LIST_MEN_FAIL = 'PRODUCT_LIST_MEN_FAIL';


export const PRODUCT_LIST_WOMEN_REQUEST = 'PRODUCT_LIST_WOMEN_REQUEST';
export const PRODUCT_LIST_WOMEN_SUCCESS = 'PRODUCT_LIST_WOMEN_SUCCESS';
export const PRODUCT_LIST_WOMEN_FAIL = 'PRODUCT_LIST_WOMEN_FAIL';


export const PRODUCT_LIST_KIDS_REQUEST = 'PRODUCT_LIST_KIDS_REQUEST';
export const PRODUCT_LIST_KIDS_SUCCESS = 'PRODUCT_LIST_KIDS_SUCCESS';
export const PRODUCT_LIST_KIDS_FAIL = 'PRODUCT_LIST_KIDS_FAIL';